[config]
reload_apps = true

[config.wallpaper]
command = "awww"
arguments = [ "img", "-t", "fade", "--transition-duration", "0.5", "--transition-step", "255", "--transition-fps", "60", "-f", "Nearest",]
set = true
[templates.hyprland]
input_path = "~/.config/Ax-Shell/config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/Ax-Shell/config/hypr/colors.conf"
[templates.waybar]                                                                                                                                                             
input_path = "~/.config/Ax-Shell/config/matugen/templates/waybar.css"                                                                                                            
output_path = "~/.config/waybar/style.css"
#[templates.ax-shell]
#input_path = "~/.config/Ax-Shell/config/matugen/templates/ax-shell.css"
#output_path = "~/.config/Ax-Shell/styles/colors.css"
#post_hook = "fabric-cli exec ax-shell 'app.set_css()' &"
[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'
[templates.swaync]                                                                                                                                                             
input_path = "~/.config/Ax-Shell/config/matugen/templates/swaync.css"                                                                                                            
output_path = "~/.config/swaync/style.css"
post_hook = 'swaync-client -rs'


[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
